### ISSUE TITLE
Heartbeat device should be part of spec

### ISSUE THREAD

**Issue by jonnew** [jonnew/ONI#5]
Device 0 would be a mandatory heartbeat device (watchdog really) who's stream cannot be disabled and has a minimum beat frequency of 10 Hz. This would allow the use of a timeout on frame reading calls which would solve deadlocking issues in the case of hardware disconnects etc.

**Comment by aacuevas** [comment]
This I am going to include in the current revision of the spec I am writing, as we are de facto following it (except it can be disabled, I think, but that's easy to fix)

**Comment by aacuevas** [comment]
This is already implemented as per the latest revision of the spec

**Comment by jonnew** [comment]
Confirmed
